### ISSUE TITLE
Remove Spotipy

### ISSUE THREAD

**Issue by mguida22** [GitSound/GitSound#28]
Would it be worth it to remove [spotipy](https://github.com/plamere/spotipy)? The project isn't maintained too well, and [spotify's web API](https://developer.spotify.com/web-api/) looks easy to interact with. It could allow us more freedom in how we interact and the ability to customize the log in process.

**Comment by biw** [comment]
Spotipy is for the Spotify web API

**Comment by biw** [comment]
Are you saying we just do the requests ourselves?

**Comment by mguida22** [comment]
Yeah handle the requests ourselves, maybe with a simple wrapper that we write. I'm running into a few issues using some of spotipy's commands when trying to pull in the tracks from a playlist.

**Comment by mguida22** [comment]
Leaving it until theres a signifigant problem.
