### ISSUE TITLE
Auto Documentation

### ISSUE THREAD

**Issue by mguida22** [GitSound/GitSound#31]
We need some generated documentation per the project description.

**Comment by nicolele** [comment]
http://sphinx-doc.org/tutorial.html
This looks like the most common thing people use for auto documentation in Python so we could try it! It generates both HTML and PDFs like the project description requires. There's also Pydoc but I'm not sure it can generate PDFs by default.

**Comment by mguida22** [comment]
@nicolele #38 got merged so you can add this now. We need to add a note in the readme of how to run it too
